#!/bin/tcsh

# function log() {
#     echo "LINENO: ${LINENO}"
#     echo "BASH_LINENO: ${BASH_LINENO[*]}"
# }

if ($# != 3) then
	echo "arg1 - questions-recognition map"
	echo "arg2 - questions list"
	echo "arg3 - question number (Q1, Q2, etc.)"
#	echo "arg4 - keyword transliterated-utf8 map"
	exit(-1)
endif

# log "$@"

set kw = illa

# log "$@"

while ($kw != aam)
	# log "$@"
	echo 107 > ../tasker.txt
	# log "$@"
	sleep 1
	# log "$@"
	set ques = `grep -w $3 $2 |cut -d "-" -f2`
	# log "$@"
	echo $ques > ../question.txt
	# log "$@"
	echo 101 > ../tasker.txt
	# log "$@"
	tcsh scripts/complete "$ques"
	# log "$@"
	# aplay chime.wav &

	set lex = `grep -w $3 $1 |cut -d " " -f2`
	# log "$@"
	./scripts/recognition lexicon/$lex
	# log "$@"
	cp keyword keyword1
	# log "$@"

	set keyword = `cat keyword`
	# log "$@"
	set dec = `cat lh_dec`
	# log "$@"
	set kw_utf8 = `grep -w $keyword lists/kw_trans_utf8_map | cut -d " " -f2-`
	# log "$@"

	if ($dec == right) then
		# log "$@"
		#set ans_display = `cat keyword`
		set kw = aam
		# log "$@"
	else
		# log "$@"
		./scripts/complete "நீங்கள் $kw_utf8 என்று கூறினீர்களா"
		# aplay chime.wav &
		# log "$@"
		./scripts/recognition lexicon/lex1
		# log "$@"
		set kw1 = `cat keyword`
		# log "$@"
		set kw = `grep -w $kw1 lists/keyword_map | cut -d " " -f1 | head -1`
		# log "$@"
		if ($kw == aam) then
			# log "$@"
			cp keyword1 keyword
			#echo $kw > ../answer.txt
			#echo 102 > ../tasker.txt
		endif
	endif
end

# log "$@"
echo $kw_utf8 > ../answer.txt
# log "$@"
echo 102 > ../tasker.txt
# log "$@"
sleep 1
# log "$@"
#set kw1 = `cat keyword1`
#grep -w $kw1 lists/keyword_map | cut -d " " -f1 | head -1 > keyword
# log "$@"
echo 103 > ../tasker.txt
# log "$@"
sleep 1
# log "$@"
rm keyword1
# log "$@"
