#!/bin/tcsh -f

if ($# != 1) then
	echo "arg1 - text to be synthesised"
#	echo "arg2 - system"
	exit(-1)
endif

rm -rf etc/text prompt-utt/* lab/* wav/* lists/gen.scp temp* lists/word lists/trans_word lists/out_word 
rm wordpronunciation

echo "$1" > temp2
#perl scripts/normalize_all.pl temp2 temp3
#cp temp3 temp2
set sentence = `cat temp2`
echo "(1 "'"'$sentence.'"'")" > lists/text


$FESTDIR/bin/festival -b festvox/build_clunits.scm '(build_prompts "lists/text")'
make
ls `pwd`/lab/1.lab > lists/gen.scp
./scripts/hts_engine.pl scripts/Config.pm
play wav/1.wav
#rm phn phone syl1 syl2 syl3 syllables temp2 temp3 
